[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --probe 2e8a:000c:0F2DEDAEAFC2FADF --protocol swd --chip RP2040" # for jtag
#runner = "elf2uf2-rs --deploy --serial --verbose" # for elf2uf2

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "trace"
